"""
Stage H — renderer. Emits sopgen/output/<stem>/guide/{steps_data.js, index.html}.

index.html is a transformed COPY of the frozen template that (a) loads the data
from steps_data.js via <script src> before the renderer (NOT fetch — file://),
(b) drops the inline declarations, (c) repoints <video src>, (d) injects a
provenance/status banner, (e) swaps the standard-time cell. The template is never
modified. A smoke test verifies the transform.
"""
from __future__ import annotations

import json
import os
import re
import shutil
from pathlib import Path

from .config import OUTPUT, TEMPLATE, REPO

VIDEO_SRC_RE = re.compile(r'src="([^"]+\.mp4)"')   # generic <video src> — any clip name (not a hardcoded literal)
GEN_MARK = "/*GEN: STEPS/CHAPTERS/SEQ/SELF from steps_data.js*/"
PAGE_ANCHOR = '<div class="page" id="page">'
ST_BIG = '<span class="big">38~45초</span>'
ST_SMALL = " 측정 중앙값 41초 · 파일럿"


def _steps_data_js(b: dict) -> str:
    def js(name, val):
        return f"var {name} = {json.dumps(val, ensure_ascii=False)};"
    return "\n".join(["/* generated by sopgen — draft work instruction, do not hand-edit */",
                      js("STEPS", b["STEPS"]), js("CHAPTERS", b["CHAPTERS"]),
                      js("SEQ", b["SEQ"]), js("SELF", b["SELF"]), ""])


def _banner(b: dict) -> str:
    r = b["review"]
    prov = " · ".join(f"{k} ×{v}" for k, v in r["provenance"].items())
    if r.get("approved"):                       # evidence ok AND human-signed
        status = "✅ 승인 완료"
        bg, bd, ink = "#e7f6ec", "#1c8a4e", "#0c5a30"
    elif r.get("evidence_ok"):                  # grounded, awaiting human sign-off (gold clip)
        status = "✓ 근거 충족 · 사람 서명 대기"
        bg, bd, ink = "#e1f3f5", "#7fc3cc", "#0e6470"
    else:                                       # ungrounded draft
        status = f"⚠ 미승인 · 검수 {len(r['needs_review'])}건 대기"
        bg, bd, ink = "#fff6c9", "#e6c64a", "#6b5600"
    dropped = f" · 풀에서 미배치 {r['dropped_pool_steps']}건" if r["dropped_pool_steps"] else ""
    st = b["standard_time"]
    return (f'<div style="background:{bg};border:1px solid {bd};color:{ink};'
            f'padding:8px 14px;margin:10px 18px;font-size:12.5px;line-height:1.5">'
            f'<b>⚙ 자동 생성 초안 (sopgen)</b> · 클립 {b["stem"][-9:]} '
            f'({b["shot_type"]} / {",".join(b["roles"])}) · 출처 {prov}{dropped} · '
            f'<b>{status}</b> · 표준시간 {st.get("display", "?")} <small>({st.get("caveat", "")})</small>'
            f'</div>')


def _transform_html(html: str, video_rel: str, b: dict) -> str:
    i_steps = html.index("const STEPS")
    i_dollar = html.index("const $=", i_steps)
    i_script = html.rindex("<script>", 0, i_steps)
    between = html[i_script + len("<script>"):i_steps]
    new = (html[:i_script] + '<script src="steps_data.js"></script>\n' + "<script>" + between
           + GEN_MARK + "\n  " + html[i_dollar:])

    m = VIDEO_SRC_RE.search(new)
    if not m:
        raise ValueError("template video src anchor missing")
    new = new[:m.start(1)] + video_rel + new[m.end(1):]
    new = new.replace(PAGE_ANCHOR, PAGE_ANCHOR + "\n  " + _banner(b), 1)
    # standard-time cell
    st = b["standard_time"].get("display", "[측정 불가]")
    new = new.replace(ST_BIG, f'<span class="big">{st}</span>', 1)
    new = new.replace(ST_SMALL, f" {b['standard_time'].get('caveat', '자동초안')}", 1)
    return new


def _smoke(index_html, steps_js, b):
    errs = []
    for cond, msg in [
        ('<script src="steps_data.js"></script>' in index_html, "external script missing"),
        (GEN_MARK in index_html, "GEN marker missing"),
        ("const STEPS = [" not in index_html, "inline const STEPS still present"),
        ('src="clip.mp4"' in index_html, "video src not repointed to clip.mp4"),
        (ST_BIG not in index_html, "standard-time cell not replaced"),
        (_banner(b)[:40] in index_html, "banner missing"),
    ]:
        if not cond:
            errs.append(msg)
    n = len(b["STEPS"])
    for label, idx in b["CHAPTERS"]:
        if not (0 <= idx < n):
            errs.append(f"CHAPTERS '{label}' index {idx} out of range")
    for name in ("STEPS", "CHAPTERS", "SEQ", "SELF"):
        marker = f"var {name} = "
        seg = steps_js[steps_js.index(marker) + len(marker):]
        seg = seg[:seg.index(";\n")].rstrip().rstrip(";")
        try:
            json.loads(seg)
        except json.JSONDecodeError as e:
            errs.append(f"{name} invalid JSON: {e}")
    return errs


def render(stem: str, bundle: dict) -> dict:
    if not TEMPLATE.exists():
        raise FileNotFoundError(f"template not found: {TEMPLATE}")
    guide = OUTPUT / stem / "guide"
    guide.mkdir(parents=True, exist_ok=True)

    # materialize the servable clip INSIDE guide/ so the http layer never traverses ../../data
    src_mp4 = REPO / bundle["video"].replace("\\", "/")
    clip_dst = guide / "clip.mp4"
    if src_mp4.is_file() and (not clip_dst.exists() or clip_dst.stat().st_size != src_mp4.stat().st_size):
        shutil.copy2(src_mp4, clip_dst)
    video_rel = "clip.mp4"                              # sibling of index.html — file:// safe, no traversal

    steps_js = _steps_data_js(bundle)
    index_html = _transform_html(TEMPLATE.read_text(encoding="utf-8"), video_rel, bundle)
    errs = _smoke(index_html, steps_js, bundle)
    if errs:
        raise AssertionError("render smoke test failed:\n  - " + "\n  - ".join(errs))

    _atomic(guide / "steps_data.js", steps_js)
    _atomic(guide / "index.html", index_html)
    _atomic(guide / "review.json", json.dumps(bundle["review"], ensure_ascii=False, indent=2))
    return {"guide_dir": str(guide), "index": str(guide / "index.html"), "video_rel": video_rel}


def _atomic(path: Path, text: str):
    tmp = path.with_suffix(path.suffix + ".tmp")
    tmp.write_text(text, encoding="utf-8")
    os.replace(tmp, path)
